// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-v3_9fGUUYHHLClNxXL1LgCNDnMH8X6E',
    appId: '1:479822435618:web:a15d03de00aba01a54817b',
    messagingSenderId: '479822435618',
    projectId: 'expenditure-management-b2312',
    authDomain: 'expenditure-management-b2312.firebaseapp.com',
    storageBucket: 'expenditure-management-b2312.appspot.com',
    measurementId: 'G-6137QSCTVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhDQ9DQ8ozSn5_wjTKuawtOCF3ZkvVQRc',
    appId: '1:676807914763:android:b673bd64b65b5976de1e0e',
    messagingSenderId: '676807914763',
    projectId: 'quanlichitieu-12ef6',
    storageBucket: 'quanlichitieu-12ef6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj5bmzci2c4ce6EgcDjcjToKcx5Wlpc-g',
    appId: '1:479822435618:ios:12bed3aa659e2ee154817b',
    messagingSenderId: '479822435618',
    projectId: 'expenditure-management-b2312',
    storageBucket: 'expenditure-management-b2312.appspot.com',
    iosClientId:
        '479822435618-5rs0eu94d3i6i3ev7dtj4ao5e799qetl.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenditureManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj5bmzci2c4ce6EgcDjcjToKcx5Wlpc-g',
    appId: '1:479822435618:ios:12bed3aa659e2ee154817b',
    messagingSenderId: '479822435618',
    projectId: 'expenditure-management-b2312',
    storageBucket: 'expenditure-management-b2312.appspot.com',
    iosClientId:
        '479822435618-5rs0eu94d3i6i3ev7dtj4ao5e799qetl.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenditureManagement',
  );
}
